# Generated by Django 5.0.2 on 2024-03-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinin",
            name="membership_period",
            field=models.CharField(
                choices=[("daily", "Daily")], default="daily", max_length=50
            ),
        ),
    ]
